name: Deploy a static page on github pages

on: 
  push:
    branches:
       - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.deployment_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure github pages
        uses: actions/configure-pages@v5

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with: 
          path: .

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Deploy the static website
        run: echo 'Static website deployed successfully'